In [3]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

# Simulated dataset
# Features: Weather condition (temp), Vegetation index (NDVI), Terrain slope, Satellite observation (reflectance)
# Target: SWE in inches

# Generate synthetic feature data
np.random.seed(42)
num_samples = 100

# Simulated features
temperature = np.random.uniform(low=-10, high=30, size=num_samples)  # Temperature in °C
ndvi = np.random.uniform(low=0, high=1, size=num_samples)  # NDVI (Normalized Difference Vegetation Index)
slope = np.random.uniform(low=0, high=30, size=num_samples)  # Terrain slope in degrees
reflectance = np.random.uniform(low=0.1, high=0.8, size=num_samples)  # Satellite reflectance (0-1)

# Combine features into a single feature matrix
features = np.column_stack((temperature, ndvi, slope, reflectance))

# Simulated SWE data (in inches), influenced by features
swe_data = (0.5 * temperature + 0.3 * ndvi - 0.2 * slope + 0.4 * reflectance + np.random.normal(scale=1, size=num_samples))

print("Original SWE data (in inches):")
print(swe_data[:10])  # Print the first 10 entries for brevity

print("\nFeatures used for training:")
print(features[:10])  # Print the first 10 entries for brevity

# Normalize SWE values to the range 0-1
max_swe = 200
swe_normalized = swe_data / max_swe

print("\nNormalized SWE data (range 0-1):")
print(swe_normalized[:10])  # Print the first 10 entries for brevity

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, swe_normalized, test_size=0.2, random_state=42)

print("\nTraining features:")
print(X_train[:10])  # Print the first 10 entries for brevity
print("Training normalized SWE values:")
print(y_train[:10])  # Print the first 10 entries for brevity
print("\nTesting features:")
print(X_test[:10])  # Print the first 10 entries for brevity
print("Testing normalized SWE values:")
print(y_test[:10])  # Print the first 10 entries for brevity

# Initialize and train the regression model
model = LinearRegression()
model.fit(X_train, y_train)

print("\nModel training complete.")

# Make predictions
y_pred_normalized = model.predict(X_test)

print("\nPredicted normalized SWE values:")
print(y_pred_normalized[:10])  # Print the first 10 entries for brevity

# Denormalize the predictions to the original SWE scale
y_pred = y_pred_normalized * max_swe

print("\nDenormalized predicted SWE values (in inches):")
print(y_pred[:10])  # Print the first 10 entries for brevity

# Calculate and print the Mean Squared Error
y_test_original = y_test * max_swe
mse = mean_squared_error(y_test_original, y_pred)

print("\nOriginal SWE values for testing set (in inches):")
print(y_test_original[:10])  # Print the first 10 entries for brevity
print(f"Mean Squared Error: {mse}")

print("\nComparison of original and predicted SWE values:")
for orig, pred in zip(y_test_original[:10], y_pred[:10]):
    print(f"Original: {orig:.2f} inches, Predicted: {pred:.2f} inches")


Original SWE data (in inches):
[ 7.99094481e-03  1.39101526e+01  9.63774415e+00  1.64262938e+00
 -4.67845968e+00 -1.67740871e+00 -4.04248207e+00  9.29476248e+00
  6.50500163e+00  1.04279175e+01]

Features used for training:
[[ 4.98160475  0.03142919 19.26094938  0.1361772 ]
 [28.02857226  0.63641041  2.52419895  0.47194824]
 [19.27975767  0.31435598  4.84886142  0.47844459]
 [13.94633937  0.50857069 26.95662566  0.54620093]
 [-3.75925438  0.90756647 18.19287179  0.60826393]
 [-3.76021919  0.24929223  0.27591155  0.78309646]
 [-7.67665551  0.41038292  3.04414629  0.46141024]
 [24.64704583  0.75555114 19.90505307  0.32606953]
 [14.04460047  0.22879817  0.15184752  0.65663034]
 [18.32290311  0.07697991  4.82424154  0.28958258]]

Normalized SWE data (range 0-1):
[ 3.99547240e-05  6.95507630e-02  4.81887208e-02  8.21314688e-03
 -2.33922984e-02 -8.38704353e-03 -2.02124104e-02  4.64738124e-02
  3.25250082e-02  5.21395876e-02]

Training features:
[[26.8749694   0.24205527 16.70403787  0.549693